---
language: python
python: "2.7"
sudo: required
dist: stretch

# Use the new container infrastructure
# sudo: false

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible

  # Check ansible version .
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Get role dependencies with ansible-galaxy
  - "ansible-galaxy install denics.htpc-common -p ../"
  - "ansible-galaxy install denics.htpc-nas -p ../"
  # Run Playbook
  - "ansible-playbook -c local tests/test.yml -i tests/inventory --K"

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/