# htpc-server.yml
---
- hosts: mediaserver
  become: yes

  pre_tasks:

  # Copy custom/custom.yml.sample to custom/custom.yml
  # Update variable values
  - name: Load custom variables from custom.yml
    include_vars: custom/custom.yml
    failed_when: false

  roles:
  - { role: denics.htpc-common}
  - { role: denics.htpc-nas, when: htpc_nas_enabled }
  - { role: denics.htpc-kodi, when: kodi_mysql_enabled }
  - { role: denics.htpc-sickrage, when: sickrage_enabled }
#  - { role: denics.radarr, when: radarr_enabled }
#  - { role: denics.htpc-nzbtomedia, when: nzbToMedia_enabled }
#  - { role: denics.deluge, when: deluge_enabled }
#  - { role: denics.sabnzbd, when: sabnzbd_enabled }
# - { role: denics.headphones, when: headphones_enabled }
##  - { role: denics.tvheadend, when: tvheadend_enabled }
#  - { role: denics.htpc-manager, when: htpc_manager_enabled }